spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PAPERWORK?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: password
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        query:
          in_clause_parameter_padding: true
        format_sql: true
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
#  lifecycle:
#    timeout-per-shutdown-phase: 30s
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 12MB
#      max-request-size: 15MB
#  profiles:
#    group:
#      default: common
#      jhc: common, common-jhc
#      alpha: common, common-alpha
#      real: common, common-real
#  thymeleaf:
#    cache: false
#  mvc:
#    contentnegotiation:
#      favor-parameter: true



